default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: web_app_development
test:
  <<: *default
  database: web_app_test

production:
  <<: *default
  database: web_app_production
  username: web_app
  password: <%= ENV['WEB_APP_DATABASE_PASSWORD'] %>
